#!/bin/sh
# helper script for convenience

# all queries (generated by ls *.sparql |xargs)
QUERIES=`ls *.sparql |xargs`
#QUERIES="beginEndIndexAreNonNegativeInteger.sparql contextHasIsString.sparql contextTypedAsRFC5147String.sparql hasReferenceContext.sparql isStringLength.sparql noNodesWithoutITSRDFAnnotation.sparql RFC5147StringHasBeginIndex.sparql RFC5147StringHasEndIndex.sparql"
for i in $QUERIES
do 
	echo "Running: $i" 
	# execute the test, if you find an error grep it
	./executeOneTest.sh expected $i | grep -C5 'http' 
	echo "Done: $i" 
done


